#
# K2HDKC
#
# Copyright 2018 Yahoo! JAPAN corporation.
#
# K2HDKC is k2hash based distributed KVS cluster.
# K2HDKC uses K2HASH, CHMPX, FULLOCK libraries. K2HDKC supports
# distributed KVS cluster server program and client libraries.
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.
#
# AUTHOR:   Takeshi Nakatani
# CREATE:   Thu Feb 1 2018
# REVISION:
#

language: cpp

sudo: required

dist: trusty

env:
  global:
    - PCUSER=antpickax
    - PCREPO=current
    - PCDLREPO=stable
  matrix:
    - OS=centos 
      TAG=centos7 
      DISTTAG=el/7 
      INSTPKG="git autoconf automake gcc gcc-c++ gdb make libtool pkgconfig redhat-rpm-config rpm-build ruby-devel rubygems procps libyaml-devel chmpx-devel nss-devel"
    - OS=centos 
      TAG=centos6 
      DISTTAG=el/6 
      INSTPKG="git autoconf automake gcc gcc-c++ gdb make libtool pkgconfig redhat-rpm-config rpm-build ruby-devel rubygems procps libyaml-devel chmpx-devel nss-devel"
    - OS=fedora 
      TAG=28 
      DISTTAG=fedora/28 
      INSTPKG="git autoconf automake gcc gcc-c++ gdb make libtool pkgconfig redhat-rpm-config rpm-build ruby-devel rubygems procps libyaml-devel chmpx-devel nss-devel"
    - OS=ubuntu 
      TAG=18.04 
      DISTTAG=ubuntu/bionic 
      INSTPKG="git autoconf autotools-dev gcc g++ make gdb dh-make fakeroot dpkg-dev devscripts libtool pkg-config ruby-dev rubygems rubygems-integration procps libyaml-dev chmpx-dev gnutls-dev"
    - OS=debian 
      TAG=stretch 
      DISTTAG=debian/stretch 
      INSTPKG="git autoconf autotools-dev gcc g++ make gdb dh-make fakeroot dpkg-dev devscripts libtool pkg-config ruby-dev rubygems rubygems-integration procps libyaml-dev chmpx-dev gnutls-dev"

cache: apt

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker image pull ${OS}:${TAG}

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export PCTOKEN=dummy_token_for_pr; else export PCTOKEN=${PACKAGECLOUD_TOKEN}; fi'
  - travis_wait 30 sleep 3600 &
  - docker container run 
    --rm=true 
    -e TRAVIS_TAG=${TRAVIS_TAG} 
    -e FORCE_BUILD_PKG=${FORCE_BUILD_PKG} 
    -e USE_PC_REPO=${USE_PC_REPO} 
    -e BUILD_NUMBER=${BUILD_NUMBER} 
    -e DEBFULLNAME=${DEBFULLNAME} 
    -e DEBEMAIL=${DEBEMAIL} 
    -e CONFIGUREOPT=${CONFIGUREOPT} 
    -e K2HATTR_ENC_TYPE=${K2HATTR_ENC_TYPE} 
    -v `pwd`:/k2hdkc:rw ${OS}:${TAG} 
    /bin/sh -c "/k2hdkc/buildutils/travis_builder.sh -${OS} -pctoken ${PCTOKEN} -pcuser ${PCUSER} -pcrepo ${PCREPO} -pcdlrepo ${PCDLREPO} -pcdist ${DISTTAG} ${INSTPKG}"

#
# VIM modelines
#
# vim:set ts=4 fenc=utf-8:
#
